[tool.black]
line-length = 105

[tool.isort]
profile = "black"
known_infra = "infra"
known_domain = "domain"
known_app = "app"
known_core = "core"
sections = "FUTURE,STDLIB,THIRDPARTY,CORE,APP,INFRA,DOMAIN,FIRSTPARTY,LOCALFOLDER"
lines_after_imports = 2
combine_as_imports = true
combine_straight_imports = true
atomic = true

